# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0002_auto_20170830_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_confirmed',
            field=models.BooleanField(default=False),
        )
    ]
