# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0003_auto_20170706_1438'),
        ('hnfp', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('employer', models.CharField(max_length=400)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField(max_length=400)),
                ('job_type', models.CharField(max_length=400)),
                ('salary', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('jop_post_doc', models.FileField(upload_to='job-post/')),
                ('apply_url', models.URLField(max_length=400)),
            ],
        ),
    ]
