# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0003_auto_20170830_1749'),
    ]

#    operations = [
 #       migrations.AddField(
  #          model_name='observation',
   #         name='observer_username',
    #        field=models.CharField(blank=True, max_length=800, null=True),
     #   ),
  #  ]
