# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 18:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0004_observation_observer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Impact Type', max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectResourceImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impactType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hnfp.ImpactType')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Resource Name', max_length=4000)),
            ],
        ),
        migrations.AlterField(
            model_name='observation',
            name='category',
            field=models.CharField(choices=[('Bear', 'bear'), ('Deer', 'deer'), ('Medicinal Herbs', 'medicinal_herbs'), ('Shrimp', 'shrimp'), ('Berries', 'berries'), ('Firewood', 'firewood'), ('Mushrooms', 'mushrooms'), ('Crab', 'crab'), ('Fish', 'fish'), ('Shellfish', 'shellfish'), ('Custom', 'custom')], default='custom', max_length=400),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Text', 'text'), ('Radio', 'radio'), ('Select', 'select'), ('Select Multiple', 'select_multiple'), ('Integer', 'integer')], default='Text', max_length=200),
        ),
        migrations.AddField(
            model_name='projectresourceimpact',
            name='resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hnfp.Resource'),
        ),
    ]
