# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 22:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0004_observation_observer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandUseProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(blank=True, max_length=300, null=True)),
                ('proj_summary', models.CharField(blank=True, default=None, max_length=20000, null=True)),
                ('proj_description', models.CharField(blank=True, default=None, max_length=20000, null=True)),
                ('proj_start_date', models.CharField(blank=True, max_length=200, null=True)),
                ('proj_completion_date', models.CharField(blank=True, max_length=200, null=True)),
                ('proj_actions', models.CharField(blank=True, max_length=20000, null=True)),
                ('proj_impact', models.CharField(blank=True, max_length=4000, null=True)),
                ('proj_dollar_costs', models.IntegerField(blank=True, null=True)),
                ('proj_value', models.CharField(blank=True, max_length=4000, null=True)),
                ('proj_published', models.BooleanField(default=False)),
                ('proj_area', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, null=True, srid=3857)),
            ],
        ),
    ]
