# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0004_aoi_jobopportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopportunity',
            name='location',
            field=models.CharField(max_length=400),
        ),
    ]
