# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 20:00
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0005_auto_20170929_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forest_use', models.CharField(blank=True, choices=[('Hunt', 'hunt_deer'), ('Gather Herbs', 'gather_herbs'), ('Fish', 'fish'), ('Collect Berries', 'collect_berries'), ('Gather Mushrooms', 'gather_mushrooms'), ('Collect Firewood', 'collect_firewood')], max_length=400, null=True)),
                ('rank_hunt', models.CharField(blank=True, max_length=400, null=True)),
                ('rank_gather_herbs', models.CharField(blank=True, max_length=400, null=True)),
                ('rank_fish', models.CharField(blank=True, max_length=400, null=True)),
                ('rank_collect_berries', models.CharField(blank=True, max_length=400, null=True)),
                ('rank_gather_mushrooms', models.CharField(blank=True, max_length=400, null=True)),
                ('rank_collect_firewood', models.CharField(blank=True, max_length=400, null=True)),
                ('gender', models.CharField(blank=True, max_length=400, null=True)),
                ('employment_forest_dependent', models.CharField(blank=True, max_length=400, null=True)),
                ('occupation', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
