# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0005_landuseprojects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landuseprojects',
            old_name='proj_actions',
            new_name='actions',
        ),
        migrations.RenameField(
            model_name='landuseprojects',
            old_name='proj_area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='landuseprojects',
            old_name='proj_completion_date',
            new_name='completion_date',
        ),
        migrations.RenameField(
            model_name='landuseprojects',
            old_name='proj_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='landuseprojects',
            old_name='proj_dollar_costs',
            new_name='dollar_costs',
        ),
        migrations.RenameField(
            model_name='landuseprojects',
            old_name='proj_impact',
            new_name='impact',
        ),
        migrations.RenameField(
            model_name='landuseprojects',
            old_name='proj_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='landuseprojects',
            old_name='proj_published',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='landuseprojects',
            old_name='proj_start_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='landuseprojects',
            old_name='proj_summary',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='landuseprojects',
            old_name='proj_value',
            new_name='value',
        ),
        migrations.AddField(
            model_name='landuseprojects',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landuseprojects',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
