# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0006_auto_20170728_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customcategory', models.CharField(max_length=400)),
                ('observation_date', models.DateTimeField()),
                ('observation_type', models.CharField(max_length=400)),
                ('observation_tally', models.IntegerField(blank=True, null=True)),
                ('observation_created', models.DateTimeField(auto_now_add=True)),
                ('observation_updated', models.DateTimeField(auto_now=True)),
                ('number_of_observers', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(max_length=1600)),
            ],
            options={
                'verbose_name_plural': 'Observations',
            },
        ),
        migrations.CreateModel(
            name='ObservationCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_category', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ObservationLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('latlng', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='jobopportunity',
            name='jop_post_doc',
            field=models.FileField(blank=True, upload_to='job-post/'),
        ),
        migrations.AddField(
            model_name='observation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hnfp.ObservationCategories'),
        ),
        migrations.AddField(
            model_name='observation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hnfp.ObservationLocations'),
        ),
    ]
