# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 22:35
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0006_auto_20171002_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyresults',
            options={'verbose_name_plural': 'Survey Responses'},
        ),
    ]
