# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0006_auto_20170922_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='landuseprojects',
            name='category',
            field=models.CharField(blank=True, choices=[('forest', 'Forest'), ('road', 'Road'), ('stream', 'Stream')], max_length=400, null=True),
        ),
    ]
