# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0007_auto_20170808_1556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObservationCategories',
            new_name='ObservationCategory',
        ),
        migrations.RenameModel(
            old_name='ObservationLocations',
            new_name='ObservationLocation',
        ),
    ]
