# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 00:15
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0007_landuseprojects_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandUseProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.CharField(blank=True, choices=[('forest', 'Forest'), ('road', 'Road'), ('stream', 'Stream')], max_length=400, null=True)),
                ('summary', models.CharField(blank=True, default=None, max_length=20000, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=20000, null=True)),
                ('start_date', models.CharField(blank=True, max_length=200, null=True)),
                ('completion_date', models.CharField(blank=True, max_length=200, null=True)),
                ('actions', models.CharField(blank=True, max_length=20000, null=True)),
                ('impact', models.CharField(blank=True, max_length=4000, null=True)),
                ('dollar_costs', models.IntegerField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=4000, null=True)),
                ('area', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, null=True, srid=3857)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Land Use Projects',
            },
        ),
        migrations.DeleteModel(
            name='LandUseProjects',
        ),
    ]
