# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 19:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0008_auto_20171002_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresults',
            name='regiontally',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
