# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0008_auto_20170808_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='observation_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='observation',
            name='number_of_observers',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
