# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0008_auto_20170923_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landuseproject',
            old_name='value',
            new_name='emdollars',
        ),
        migrations.AddField(
            model_name='landuseproject',
            name='impact_change',
            field=models.CharField(blank=True, choices=[('increase', 'Increase'), ('decrease', 'Decrease'), ('no change', 'No Change')], max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='landuseproject',
            name='impact',
            field=models.CharField(blank=True, choices=[('deer', 'Deer'), ('berries', 'Berries'), ('materials', 'Raw materials'), ('water', 'Fresh water'), ('medicinal', 'Medicinal herbs'), ('sequestration', 'Carbon sequestration'), ('soil', 'Soil erosion and fertility'), ('protection', 'Reduce damage caused by extreme events'), ('climate', 'Climate and air quality'), ('pollination', 'Pollination'), ('water_treatment', 'Water treatment'), ('biological_control', 'Biological control'), ('habitat', 'Habitat for species'), ('diversity', 'Maintenance of genetic diversity'), ('tourism', 'Tourism'), ('culture', 'Aesthetic appreciation and inspiration for culture'), ('spiritual', 'Spiritual experience and identity'), ('recreation', 'Recreation')], max_length=4000, null=True),
        ),
    ]
