# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0009_auto_20171003_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='observation_photo',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='observations/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='surveyresults',
            name='forest_use_other',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='surveyresults',
            name='rank_other',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
