# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 15:52
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0010_auto_20171024_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_time', models.CharField(blank=True, max_length=20, null=True)),
                ('alert_type', models.CharField(blank=True, max_length=400, null=True)),
                ('alert_created', models.DateTimeField(auto_now_add=True)),
                ('alert_updated', models.DateTimeField(auto_now=True)),
                ('alert_username', models.CharField(blank=True, max_length=800, null=True)),
                ('alert_location', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=3857)),
                ('alert_comment', models.CharField(blank=True, default=None, max_length=20000, null=True)),
                ('alert_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Alerts',
            },
        ),
        migrations.CreateModel(
            name='LandUseProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.CharField(blank=True, choices=[('Forest', 'forest'), ('Road', 'road'), ('Stream', 'stream')], max_length=400, null=True)),
                ('summary', models.CharField(blank=True, default=None, max_length=20000, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=20000, null=True)),
                ('start_date', models.CharField(blank=True, max_length=200, null=True)),
                ('completion_date', models.CharField(blank=True, max_length=200, null=True)),
                ('actions', models.CharField(blank=True, max_length=20000, null=True)),
                ('dollar_costs', models.CharField(blank=True, max_length=4000, null=True)),
                ('emdollars', models.CharField(blank=True, max_length=4000, null=True)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(blank=True, default=None, null=True, srid=3857)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Land Use Projects',
            },
        ),
        migrations.AddField(
            model_name='observation',
            name='observer_username',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
