# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0010_auto_20170926_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landuseproject',
            name='projectResourceImpact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hnfp.ProjectResourceImpact'),
        ),
    ]
