# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0010_auto_20170809_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observation_photo',
            field=models.FileField(blank=True, default='', upload_to='observation/'),
            preserve_default=False,
        ),
    ]
