# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 19:28
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('hnfp', '0011_auto_20170927_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='landuseproject',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hnfp_landuseproject_related', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='landuseproject',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landuseproject',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AddField(
            model_name='landuseproject',
            name='geometry_final',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857, verbose_name='Final Polygon Geometry'),
        ),
        migrations.AddField(
            model_name='landuseproject',
            name='geometry_orig',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857, verbose_name='Original Polygon Geometry'),
        ),
        migrations.AddField(
            model_name='landuseproject',
            name='manipulators',
            field=models.TextField(blank=True, help_text='csv list of manipulators to be applied', null=True, verbose_name='Manipulator List'),
        ),
        migrations.AddField(
            model_name='landuseproject',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landuseproject',
            name='sharing_groups',
            field=models.ManyToManyField(blank=True, editable=False, related_name='hnfp_landuseproject_related', to='auth.Group', verbose_name='Share with the following groups'),
        ),
        migrations.AddField(
            model_name='landuseproject',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hnfp_landuseproject_related', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectresourceimpact',
            name='impactType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hnfp.ImpactType'),
        ),
        migrations.AlterField(
            model_name='projectresourceimpact',
            name='resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hnfp.Resource'),
        ),
    ]
