# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0011_auto_20170809_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='observation_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='customcategory',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observation_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observation_photo',
            field=models.FileField(blank=True, null=True, upload_to='observation/'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observation_type',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
