# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0012_auto_20170810_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observers',
            field=models.CharField(default=1, max_length=800),
        ),
    ]
