# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 22:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hnfp', '0012_alert_alert_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareObservationWithManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='landuseproject',
            name='category',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
