# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 19:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0012_auto_20170927_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landuseproject',
            name='area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, null=True, srid=3857, verbose_name='project area'),
        ),
    ]
