# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 01:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0013_auto_20171102_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landuseproject',
            name='area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, null=True, srid=3857),
        ),
    ]
