# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 20:03
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0012_auto_20170810_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='category',
            field=models.CharField(choices=[('bear', 'Bear'), ('deer', 'Dear'), ('medicinal_herbs', 'Medicinal Herbs'), ('shrimp', 'Shrimp'), ('berries', 'Berries'), ('firewood', 'Firewood'), ('mushrooms', 'Mushrooms'), ('crab', 'Crab'), ('fish', 'Fish'), ('shellfish', 'Shellfish'), ('custom', 'Custom')], default='custom', max_length=400),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observation_photo',
            field=models.ImageField(blank=True, null=True, upload_to='observation/'),
        ),
    ]
