# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 20:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0015_auto_20170816_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='location',
        ),
        migrations.AddField(
            model_name='observation',
            name='observation_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
