# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-13 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0015_landuseproject_share_with_land_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresults',
            name='forest_use',
            field=models.CharField(blank=True, choices=[('Hunt', 'hunt_deer'), ('Gather Herbs', 'gather_herbs'), ('Fish', 'fish'), ('Collect Berries', 'collect_berries'), ('Gather Mushrooms', 'gather_mushrooms'), ('Collect Firewood', 'collect_firewood'), ('Other/None', 'other')], default='Select Multiple', max_length=400, null=True),
        ),
    ]
