# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0015_auto_20170927_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landuseproject',
            name='dollar_costs',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
