# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-13 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0016_auto_20180413_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresults',
            name='forest_use',
        ),
        migrations.AddField(
            model_name='surveyresults',
            name='forest_use_collect_berries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyresults',
            name='forest_use_collect_firewood',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyresults',
            name='forest_use_fish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyresults',
            name='forest_use_gather_herbs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyresults',
            name='forest_use_gather_mushrooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyresults',
            name='forest_use_hunt_deer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyresults',
            name='forest_use_none_other',
            field=models.BooleanField(default=False),
        ),
    ]
