# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0016_auto_20170816_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observation_photo',
            field=models.FileField(blank=True, null=True, upload_to='observation/'),
        ),
    ]
