# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-13 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0017_auto_20180413_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyresults',
            old_name='forest_use_none_other',
            new_name='forest_use_other_activities',
        ),
    ]
