# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-13 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0018_auto_20180413_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresults',
            name='forest_use_collect_berries',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresults',
            name='forest_use_collect_firewood',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresults',
            name='forest_use_fish',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresults',
            name='forest_use_gather_herbs',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresults',
            name='forest_use_gather_mushrooms',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresults',
            name='forest_use_hunt_deer',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresults',
            name='forest_use_other_activities',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
