# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 23:02
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0019_auto_20170819_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observation_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=3857),
        ),
    ]
