# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0020_auto_20170820_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='comments',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
