# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-15 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnfp', '0020_auto_20180514_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_event',
            field=models.BooleanField(default=False, verbose_name='event'),
        ),
    ]
