module.exports = {
    'globDirectory': '.',
    "globPatterns": [
        "**/*.{js,css,png,jpg,html}"
    ],
    'globIgnores': [
        'assets/**',
        'bower_components/**',
        'workbox-config.js',
        'static/sw.js',
    ],
    'templatedUrls': {
        '/': [
            // 'templates/base.html',
            // 'templates/hnfp/index.html',
            'templates/hnfp/blocks/extra_head.html',
            'templates/hnfp/blocks/extra_css.html',
            'templates/hnfp/blocks/footer.html',
            'templates/hnfp/blocks/extra_js.html',
            'templates/hnfp/blocks/logos.html',
            'static/**/*.css',
            'static/**/*.js',
            'static/**/*.png',
            'static/**/*.jpg',
            'static/**/*.svg',
            'static/**/*.json',
        ],
        '/dashboard': [
            // 'templates/base.html',
            // 'templates/hnfp/index.html',
            'templates/hnfp/blocks/extra_css.html',
            'templates/hnfp/blocks/extra_head.html',
            'templates/hnfp/blocks/extra_js.html',
            // 'templates/hnfp/blocks/navbar.html',
            'templates/hnfp/blocks/logos.html',
            'templates/hnfp/blocks/footer.html',
            'templates/hnfp/blocks/observation_icons.html',
            'templates/hnfp/dashboard/alerts.html',
            'templates/hnfp/dashboard/blog.html',
            'templates/hnfp/dashboard/events.html',
            'templates/hnfp/dashboard/observation.html',
            'templates/hnfp/dashboard/open_positions.html',
            'templates/hnfp/dashboard/weather.html',
            'static/**/*.css',
            'static/**/*.js',
            'static/**/*.png',
            'static/**/*.jpg',
            'static/**/*.svg',
            'static/**/*.json',
        ],
        '/dashboard/': [
            // 'templates/base.html',
            // 'templates/hnfp/index.html',
            'templates/hnfp/blocks/extra_css.html',
            'templates/hnfp/blocks/extra_head.html',
            'templates/hnfp/blocks/extra_js.html',
            'templates/hnfp/blocks/logos.html',
            'templates/hnfp/blocks/footer.html',
            'templates/hnfp/blocks/observation_icons.html',
            'templates/hnfp/dashboard/alerts.html',
            'templates/hnfp/dashboard/blog.html',
            'templates/hnfp/dashboard/events.html',
            'templates/hnfp/dashboard/observation.html',
            'templates/hnfp/dashboard/open_positions.html',
            'templates/hnfp/dashboard/weather.html',
            'static/**/*.css',
            'static/**/*.js',
            'static/**/*.png',
            'static/**/*.jpg',
            'static/**/*.svg',
            'static/**/*.json',
        ],
        '/home': [
            // 'templates/base.html',
            // 'templates/hnfp/index.html',
            'templates/hnfp/blocks/extra_head.html',
            'templates/hnfp/blocks/extra_css.html',
            'templates/hnfp/blocks/footer.html',
            'templates/hnfp/blocks/extra_js.html',
            'templates/hnfp/blocks/logos.html',
            'static/**/*.css',
            'static/**/*.js',
            'static/**/*.png',
            'static/**/*.jpg',
            'static/**/*.svg',
            'static/**/*.json',
        ],
        '/account/': [
        //     'templates/base.html',
        //     'templates/hnfp/index.html',
            'templates/hnfp/blocks/extra_head.html',
            'templates/hnfp/blocks/extra_css.html',
            'templates/hnfp/blocks/footer.html',
            'templates/hnfp/blocks/extra_js.html',
            '../../mp-accounts/accounts/templates/accounts/login_form.html',
            '../../mp-accounts/accounts/templates/accounts/index.html',
            'static/**/*.css',
            'static/**/*.js',
            'static/**/*.png',
            'static/**/*.jpg',
            'static/**/*.svg',
            'static/**/*.json',
        ],
        '/observation': [
            // 'templates/base.html',
            // 'templates/hnfp/index.html',
            'templates/hnfp/blocks/extra_head.html',
            'templates/hnfp/blocks/extra_css.html',
            'templates/hnfp/blocks/footer.html',
            'templates/hnfp/blocks/extra_js.html',
            'templates/hnfp/blocks/logos.html',
            'templates/hnfp/blocks/observation_icons.html',
            'templates/hnfp/observation.html',
            'templates/hnfp/observation_update.html',
            'templates/hnfp/observation_confirm_delete.html',
            'templates/hnfp/new_observation.html',
            'static/**/*.css',
            'static/**/*.js',
            'static/**/*.png',
            'static/**/*.jpg',
            'static/**/*.svg',
            'static/**/*.json',
        ],
        '/observation/new/': [
            // 'templates/base.html',
            // 'templates/hnfp/index.html',
            'templates/hnfp/blocks/extra_head.html',
            'templates/hnfp/blocks/extra_css.html',
            'templates/hnfp/blocks/footer.html',
            'templates/hnfp/blocks/extra_js.html',
            'templates/hnfp/blocks/logos.html',
            'templates/hnfp/blocks/observation_icons.html',
            'templates/hnfp/observation.html',
            'templates/hnfp/new_observation.html',
            'templates/hnfp/observation_confirm_delete.html',
            'templates/hnfp/observation_update.html',
            'static/**/*.css',
            'static/**/*.js',
            'static/**/*.png',
            'static/**/*.jpg',
            'static/**/*.svg',
            'static/**/*.json',
        ],
        '/alert': [
            // 'templates/base.html',
            // 'templates/hnfp/index.html',
            'templates/hnfp/blocks/extra_head.html',
            'templates/hnfp/blocks/extra_css.html',
            'templates/hnfp/blocks/footer.html',
            'templates/hnfp/blocks/extra_js.html',
            'templates/hnfp/blocks/logos.html',
            'templates/hnfp/alert.html',
            'templates/hnfp/new_alert.html',
            'templates/hnfp/alert_update.html',
            'templates/hnfp/alert_confirm_delete.html',
            'static/**/*.css',
            'static/**/*.js',
            'static/**/*.png',
            'static/**/*.jpg',
            'static/**/*.svg',
            'static/**/*.json',
        ],
        '/alert/new': [
            // 'templates/base.html',
            // 'templates/hnfp/index.html',
            'templates/hnfp/blocks/extra_head.html',
            'templates/hnfp/blocks/extra_css.html',
            'templates/hnfp/blocks/footer.html',
            'templates/hnfp/blocks/extra_js.html',
            'templates/hnfp/blocks/logos.html',
            'templates/hnfp/blocks/observation_icons.html',
            'templates/hnfp/alert_confirm_delete.html',
            'templates/hnfp/alert_update.html',
            'templates/hnfp/alert.html',
            'templates/hnfp/new_alert.html',
            'static/**/*.css',
            'static/**/*.js',
            'static/**/*.png',
            'static/**/*.jpg',
            'static/**/*.svg',
            'static/**/*.json',
        ],
    },
    'maximumFileSizeToCacheInBytes': 40 * 1024 * 1024, // 40mb max size
    'swDest': 'static/sw.min.js',
    'swSrc': 'static/sw.js',
};
